### ISSUE TITLE
Table beaker_cache is already defined for this MetaData instance

### ISSUE THREAD

**Issue by EndenDragon** [bbangert/beaker#127]
Recently, my console has been spamming quite a few of these.

```2017-04-29 07:58:56,537 :[2017-04-29 07:58:56,528] ERROR in app: Exception on /api/fetch [GET]
2017-04-29 07:58:56,538 :Traceback (most recent call last):
2017-04-29 07:58:56,539 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2017-04-29 07:58:56,539 :    response = self.full_dispatch_request()
2017-04-29 07:58:56,539 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-04-29 07:58:56,539 :    rv = self.handle_user_exception(e)
2017-04-29 07:58:56,539 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-04-29 07:58:56,540 :    reraise(exc_type, exc_value, tb)
2017-04-29 07:58:56,540 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-04-29 07:58:56,541 :    rv = self.dispatch_request()
2017-04-29 07:58:56,541 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2017-04-29 07:58:56,541 :    return self.view_functions[rule.endpoint](**req.view_args)
2017-04-29 07:58:56,542 :  File "/home/EndenDragon/Titan/titanembeds/decorators.py", line 14, in decorated_function
2017-04-29 07:58:56,542 :    return f(*args, **kwargs)
2017-04-29 07:58:56,542 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 442, in __inner
2017-04-29 07:58:56,543 :    return obj(*a, **k)
2017-04-29 07:58:56,543 :  File "/home/EndenDragon/Titan/titanembeds/blueprints/api/api.py", line 264, in fetch
2017-04-29 07:58:56,543 :    chan = filter_guild_channel(guild_id, channel_id)
2017-04-29 07:58:56,544 :  File "/home/EndenDragon/Titan/titanembeds/blueprints/api/api.py", line 193, in filter_guild_channel
2017-04-29 07:58:56,544 :    channels = get_guild_channels(guild_id)
2017-04-29 07:58:56,545 :  File "/home/EndenDragon/Titan/titanembeds/blueprints/api/api.py", line 125, in get_guild_channels
2017-04-29 07:58:56,545 :    guild_channels = discord_api.get_guild_channels(guild_id)['content']
2017-04-29 07:58:56,545 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/cache.py", line 563, in cached
2017-04-29 07:58:56,545 :    cache[0] = manager.get_cache(namespace, **options)
2017-04-29 07:58:56,546 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/cache.py", line 391, in get_cache
2017-04-29 07:58:56,546 :    return Cache._get_cache(name, kw)
2017-04-29 07:58:56,546 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/cache.py", line 309, in _get_cache
2017-04-29 07:58:56,547 :    cache_managers[key] = cache = cls(namespace, **kw)
2017-04-29 07:58:56,547 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/cache.py", line 298, in __init__
2017-04-29 07:58:56,547 :    self.namespace = cls(namespace, **nsargs)
2017-04-29 07:58:56,548 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/ext/database.py", line 101, in __init__
2017-04-29 07:58:56,548 :    self.cache = DatabaseNamespaceManager.tables.get(table_key, make_cache)
2017-04-29 07:58:56,548 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/util.py", line 166, in get
2017-04-29 07:58:56,551 :    return self.sync_get(key, createfunc, *args, **kwargs)
2017-04-29 07:58:56,551 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/util.py", line 177, in sync_get
2017-04-29 07:58:56,551 :    return self._create(key, createfunc, *args, **kwargs)
2017-04-29 07:58:56,551 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/util.py", line 184, in _create
2017-04-29 07:58:56,551 :    self[key] = obj = createfunc(*args, **kwargs)
2017-04-29 07:58:56,553 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/beaker/ext/database.py", line 94, in make_cache
2017-04-29 07:58:56,553 :    schema=schema_name if schema_name else meta.schema
2017-04-29 07:58:56,553 :  File "/home/EndenDragon/.virtualenvs/titanembeds/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 421, in __new__
2017-04-29 07:58:56,553 :    "existing Table object." % key)
2017-04-29 07:58:56,553 :InvalidRequestError: Table 'beaker_cache' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
I am speculating that it is trying to recreate the table even though it already exists. Anyhow, is there a way to fix this error?

**Comment by EndenDragon** [comment]
Is it possible to create the table during init and not during cache creation?
https://github.com/bbangert/beaker/blob/master/beaker/ext/database.py#L87

**Comment by bjamesvERT** [comment]
Intermittently seeing the same issue with sessions (not cache) in beaker 1.8.1 & sqlite3 backend, on Continuum Analytics Python3.4.5 with sqlalchemy 1.1.12

Unclear what is triggering the issue. Two mod_wsgi daemon mode processes seem to operate fine 99.9% of the time.
Reload of Apache daemon temporarily clears the failure, for some while.
Not yet able to intentionally reproduced the issue. Two Waitress wsgi server processes concurrently accessing the same db file seem to work fine 100%

Apache log excerpt:
```
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**] mod_wsgi (pid=7297): Exception occurred processing WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py'.
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**] Traceback (most recent call last):
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/middleware.py", line 156, in __call__
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     return self.wrap_app(environ, session_start_response)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/falcon/api.py", line 247, in __call__
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     start_response(resp.status, headers)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/middleware.py", line 150, in session_start_response
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     session.persist()
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/session.py", line 802, in persist
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     self._session().save()
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/session.py", line 448, in save
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     **self.namespace_args)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/ext/database.py", line 101, in __init__
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     self.cache = DatabaseNamespaceManager.tables.get(table_key, make_cache)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/util.py", line 166, in get
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     return self.sync_get(key, createfunc, *args, **kwargs)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/util.py", line 177, in sync_get
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     return self._create(key, createfunc, *args, **kwargs)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/util.py", line 184, in _create
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     self[key] = obj = createfunc(*args, **kwargs)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/beaker/ext/database.py", line 94, in make_cache
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     schema=schema_name if schema_name else meta.schema
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]   File "/var/www/wsgi-scripts/warehouse/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/sqlalchemy/sql/schema.py", line 421, in __new__
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**]     "existing Table object." % key)
[Thu Jul 13 11:52:44 2017] [error] [client **IP_REMOVED**] sqlalchemy.exc.InvalidRequestError: Table 'beaker_cache' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
