### ISSUE TITLE
Lustre File Locking

### ISSUE THREAD

**Issue by crutching** [bbangert/beaker#161]
Getting following error message trying to lock file before a citation is displayed.  We are working on a lustre fs, which i assume is the problem.

```galaxy.managers.citations ERROR 2018-05-16 15:04:19,348 [p:19455,w:2,m:0] [MainThread] Failed to fetch bibtex for DOI 10.1101/201178
Traceback (most recent call last):
  File "~/lustre1/galaxydev/galaxy/lib/galaxy/managers/citations.py", line 149, in to_bibtex
    self.raw_bibtex = self.doi_cache.get_bibtex(self.__doi)
  File "~/lustre1/galaxydev/galaxy/lib/galaxy/managers/citations.py", line 55, in get_bibtex
    return self._cache.get(key=doi, createfunc=createfunc)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/beaker/cache.py", line 317, in get
    return self._get_value(key, **kw).get_value()
  File "/galaxy/.venv/local/lib/python2.7/site-packages/beaker/container.py", line 330, in get_value
    self.namespace.acquire_read_lock()
  File "/galaxy/.venv/local/lib/python2.7/site-packages/beaker/container.py", line 204, in acquire_read_lock
    self.access_lock.acquire_read_lock()
  File "/galaxy/.venv/local/lib/python2.7/site-packages/beaker/synchronization.py", line 154, in acquire_read_lock
    x = self.do_acquire_read_lock(wait)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/beaker/synchronization.py", line 251, in do_acquire_read_lock
    fcntl.flock(filedescriptor, fcntl.LOCK_SH)
IOError: [Errno 38] Function not implemented```

**Comment by amol-** [comment]
Are you sure you are mounting the file system with the `flock` option? Should be needed to enable file locks on lustre.
