### ISSUE TITLE
DBM tests are failing on macOS

### ISSUE THREAD

**Issue by Mic92** [bbangert/beaker#166]
```
======================================================================
ERROR: tests.test_cache.test_upgrade
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/zx08zp64vl52jnvwgy485wx6l4q842zh-python3.6-nose-1.3.7/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/tests/test_cache.py", line 283, in test_upgrade
    test(os.path.join(dir, 'db'))
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/tests/test_cache.py", line 289, in _test_upgrade_has_key
    assert cache.has_key('foo')
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/beaker/cache.py", line 368, in has_key
    return key in self
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/beaker/cache.py", line 365, in __contains__
    return self._get_value(key).has_current_value()
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/beaker/container.py", line 304, in has_current_value
    self.namespace.acquire_read_lock()
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/beaker/container.py", line 208, in acquire_read_lock
    self.open('r', checkcount=True)
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/beaker/container.py", line 240, in open
    self.do_open(flags, replace)
  File "/private/tmp/nix-build-python3.6-Beaker-1.10.0.drv-0/source/beaker/container.py", line 585, in do_open
    self.dbm = self.dbmmodule.open(self.file, flags)
  File "/nix/store/0mha803yql9q7b6h93m8940z3sjbhiy8-python3-3.6.6/lib/python3.6/dbm/__init__.py", line 85, in open
    raise error[0]("need 'c' or 'n' flag to open new db")
dbm.error: need 'c' or 'n' flag to open new db
```

full log: https://logs.nix.ci/?key=nixos/nixpkgs.50537&attempt_id=f3a1165f-030e-4003-8d97-07b3ae8bf468

Linux seems fine.

**Comment by Mic92** [comment]
Noticed in https://github.com/NixOS/nixpkgs/pull/50537

**Comment by Mic92** [comment]
bump
