### ISSUE TITLE
use_cookies problem

### ISSUE THREAD

**Issue by nesiax** [bbangert/beaker#27]
Hello, i am implementing session in a xml-rpc pyramid application, everything works fine, but i don't want to use cookies since i am using xml-rpc clients, and i will handle the session id throuthg xml-rpc calls instead of using cookies, if i put a 

beaker.session.use_cookies = False

inside the pyramid .ini application i got the error shown bellow.

I don't think this is a pyramid problem, since pyramid_beaker is just a wrapper and the error is triggered at SessionObject definition inside session.py 

I use Beaker-1.6.4-py2.6.egg

Look at use_cookies = True param.

```python
               self.__dict__['_sess'] = Session(req, use_cookies=True,
                                                 **params)
```

```python
Traceback (most recent call last):
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid_tm-0.4-py2.6.egg/pyramid_tm/__init__.py", line 95, in tm_tween
    response = handler(request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/config/views.py", line 609, in __call__
    return view(context, request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/config/views.py", line 307, in attr_view
    return view(context, request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/config/views.py", line 280, in predicate_wrapper
    return view(context, request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/config/views.py", line 333, in rendered_view
    result = view(context, request)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid_rpc-0.3.1-py2.6.egg/pyramid_rpc/api.py", line 82, in _nonclass_view
    response = self.mapply(view, params, keywords)
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/pyramid_rpc-0.3.1-py2.6.egg/pyramid_rpc/api.py", line 137, in mapply
    return ob(*args)
  File "/home/ndiaz/pyramid/Partner/partner/__init__.py", line 113, in say_hello
    print request.session
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/Beaker-1.6.4-py2.6.egg/beaker/session.py", line 677, in __repr__
    return self._session().__repr__()
  File "/home/ndiaz/pyramid/lib/python2.6/site-packages/Beaker-1.6.4-py2.6.egg/beaker/session.py", line 655, in _session
    **params)
TypeError: type object got multiple values for keyword argument 'use_cookies'
```

**Comment by delijati** [comment]
I have the same error, but i think it should be addressed in https://github.com/Pylons/pyramid_beaker !?

**Comment by amol-** [comment]
https://github.com/bbangert/beaker/commit/339406c7def151d505503a2cb1dbbe04cc31680e should handle this, will check if it has no side-effects before releasing a new version.
