### ISSUE TITLE
test_cookies_enabled fails in 1.7.0 under py3.4

### ISSUE THREAD

**Issue by idella** [bbangert/beaker#78]
```bash
 * python3_4: running distutils-r1_run_phase python_test
....................................................................................S.............F../mnt/gen2/TmpDir/portage/dev-python/beaker-1.7.0-r1/work/beaker-1.7.0dev-python3_4/tests/test_session.py:19: BeakerWarning: Invalidating corrupt session d32656da7e614fd4af4652a5a1d1ce50; error was: pickle data was truncated.  Set invalidate_corrupt=False to propagate this exception.
  return Session({}, **options)
................
======================================================================
FAIL: Test if cookies are sent out properly when ``use_cookies``
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/beaker-1.7.0-r1/work/beaker-1.7.0dev-python3_4/tests/test_session.py", line 221, in test_cookies_enabled
    assert 'secure' in session.request['cookie_out']
AssertionError

----------------------------------------------------------------------
Ran 117 tests in 155.353s

FAILED (SKIP=1, failures=1)
```

I may have had this pass 3 weeks ago but I have no records of proof.
Can you replicate?
Do you require any further info?

**Comment by amol-** [comment]
Might it be that your test dir was not clean?
All tests are correclty passing on travis ( https://travis-ci.org/bbangert/beaker ) and seem to be correctly passing on my machine with a clean py3.4 env:

```
...
Test if cookies are sent out properly when ``use_cookies`` ... ok
Test that no cookies are sent when ``use_cookies`` is set to ``False`` ... ok
Test the file-based backend with session, ... ok
tests.test_session.test_invalidate_corrupt ... /media/sf_wrk/tg/beaker-upstream/tests/test_session.py:19: BeakerWarning: Invalidating corrupt session 49ac3558da364b8a9a835ef78b17e748; error was: pickle data was truncated.  Set invalidate_corrupt=False to propagate this exception.
  return Session({}, **options)
ok
tests.test_sqla.test_cache_manager ... ok
tests.test_sqla.test_increment ... ok
tests.test_sqla.test_has_key ... ok
tests.test_sqla.test_has_key_multicache ... ok
tests.test_sqla.test_clear ... ok
tests.test_sqla.test_unicode_keys ... ok
tests.test_syncdict.test_dict ... ok
tests.test_syncdict.test_weakdict ... ok
tests.test_synchronizer.test_reentrant_file ... ok
tests.test_synchronizer.test_null ... ok
tests.test_synchronizer.test_mutex ... ok
tests.test_unicode_cache_keys.test_A_unicode_encode_key_str ... ok
we replace the offending character with other non ascii one. Since ... ok
We again test the same stuff but this time we use ... ok
Invalidate cache ... ok

----------------------------------------------------------------------
Ran 117 tests in 153.086s

OK (SKIP=1)
```
