### ISSUE TITLE
apparent regression of in test_session.py under py3.4 in latest release

### ISSUE THREAD

**Issue by idella** [bbangert/beaker#86]
```bash
  DeprecationWarning)
SS....................................................S..SSS....SSS.............F../mnt/gen2/TmpDir/portage/dev-python/beaker-1.7.0-r1/work/beaker-1.7.0dev-python3_4/tests/test_session.py:19: BeakerWarning: Invalidating corrupt session a585bf81f5284b58854808d56c90cf7d; error was: pickle data was truncated.  Set invalidate_corrupt=False to propagate this exception.
  return Session({}, **options)
.SS.............
======================================================================
FAIL: Test if cookies are sent out properly when ``use_cookies``
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/beaker-1.7.0-r1/work/beaker-1.7.0dev-python3_4/tests/test_session.py", line 221, in test_cookies_enabled
    assert 'secure' in session.request['cookie_out']
nose.proxy.AssertionError: 
    # test for secure
    {'_accessed_time': 1439640172.395836, '_creation_time': 1439640172.395836} = get_session(use_cookies=True, secure=True)
>>  assert 'secure' in {'_accessed_time': 1439640172.395836, '_creation_time': 1439640172.395836}.request['cookie_out']
    

----------------------------------------------------------------------
Ran 99 tests in 153.765s

FAILED (SKIP=11, failures=1)
```

To my knowledge this passed earlier in the year.  The python used here is 3.4.3 and I suspect 3.4.2 was used then.

Do you require any further information

**Comment by amol-** [comment]
Thanks for pointing this out, it is not strictly a regression as Secure option is still working, it's just that Python 3.4.3+ now output it as "Secure" instead of "secure". See http://bugs.python.org/issue23250

https://github.com/bbangert/beaker/commit/714f464cac9d14e338cf4420163292acaab3bb49 should fix this.

**Comment by idella** [comment]
Very good patch applied
